/** Firestore collection names for Revenue & Opportunities (Admin SDK only). */

export const REVENUE_CAMPAIGNS_COLLECTION = "revenueCampaigns";
export const REVENUE_CAMPAIGN_RUNS_COLLECTION = "revenueCampaignRuns";
export const REVENUE_OPPORTUNITIES_COLLECTION = "revenueOpportunities";
export const REVENUE_OUTREACH_ACTIVITIES_COLLECTION = "revenueOutreachActivities";
export const REVENUE_EMAIL_THREADS_COLLECTION = "revenueEmailThreads";
export const REVENUE_GMAIL_CONNECTIONS_COLLECTION = "revenueGmailConnections";
export const REVENUE_FOLLOW_UP_TASKS_COLLECTION = "revenueFollowUpTasks";
export const REVENUE_DISCOVERY_SESSIONS_COLLECTION = "revenueDiscoverySessions";
export const REVENUE_OPPORTUNITY_PROPOSALS_COLLECTION = "revenueOpportunityProposals";
export const REVENUE_AGENT_RUNS_COLLECTION = "revenueAgentRuns";
export const REVENUE_WORKFLOW_RUNS_COLLECTION = "revenueWorkflowRuns";
export const REVENUE_FEEDBACK_EVENTS_COLLECTION = "revenueFeedbackEvents";
export const REVENUE_SUPPRESSION_LIST_COLLECTION = "revenueSuppressionList";
export const REVENUE_DAILY_BRIEFS_COLLECTION = "revenueDailyBriefs";
export const REVENUE_WEEKLY_BRIEFS_COLLECTION = "revenueWeeklyBriefs";
export const REVENUE_BUSINESS_PROFILES_COLLECTION = "revenueBusinessProfiles";
export const REVENUE_MEETINGS_COLLECTION = "revenueMeetings";

export const REVENUE_COLLECTIONS = [
  REVENUE_CAMPAIGNS_COLLECTION,
  REVENUE_CAMPAIGN_RUNS_COLLECTION,
  REVENUE_OPPORTUNITIES_COLLECTION,
  REVENUE_OUTREACH_ACTIVITIES_COLLECTION,
  REVENUE_EMAIL_THREADS_COLLECTION,
  REVENUE_GMAIL_CONNECTIONS_COLLECTION,
  REVENUE_FOLLOW_UP_TASKS_COLLECTION,
  REVENUE_DISCOVERY_SESSIONS_COLLECTION,
  REVENUE_OPPORTUNITY_PROPOSALS_COLLECTION,
  REVENUE_AGENT_RUNS_COLLECTION,
  REVENUE_WORKFLOW_RUNS_COLLECTION,
  REVENUE_FEEDBACK_EVENTS_COLLECTION,
  REVENUE_SUPPRESSION_LIST_COLLECTION,
  REVENUE_DAILY_BRIEFS_COLLECTION,
  REVENUE_WEEKLY_BRIEFS_COLLECTION,
  REVENUE_BUSINESS_PROFILES_COLLECTION,
  REVENUE_MEETINGS_COLLECTION,
] as const;
