/**
 * Production agreement legal language for Insight Media Group LLC deals.
 * Have licensed counsel review before relying on these terms in live client work.
 */

export const PRODUCER_LEGAL_NAME = "Insight Media Group LLC";

export const AGREEMENT_PREAMBLE_CLIENT = `This Client Project Agreement ("Agreement") is entered into as of the date of the last signature below by and between ${PRODUCER_LEGAL_NAME}, a North Carolina limited liability company ("Producer"), and the client identified as a party hereto ("Client"). Producer and Client may each be referred to as a "Party" and together as the "Parties."

BY SIGNING BELOW, EACH PARTY ACKNOWLEDGES THAT IT HAS READ, UNDERSTANDS, AND AGREES TO BE BOUND BY THIS AGREEMENT, INCLUDING ALL EXHIBITS, SCHEDULES, AND INCORPORATED TERMS. IF CLIENT IS A COMPANY, THE INDIVIDUAL SIGNING BELOW REPRESENTS THAT THEY HAVE AUTHORITY TO BIND CLIENT.`;

export const AGREEMENT_PREAMBLE_INTERNAL = `This Production Collaboration Agreement ("Agreement") is entered into as of the date of the last signature below by and among ${PRODUCER_LEGAL_NAME} and the production collaborators identified as parties hereto (each a "Party" and collectively the "Parties") for the single project described herein.

BY SIGNING BELOW, EACH PARTY ACKNOWLEDGES THAT IT HAS READ, UNDERSTANDS, AND AGREES TO BE BOUND BY THIS AGREEMENT. THE INDIVIDUAL SIGNING FOR A COMPANY REPRESENTS THAT THEY HAVE AUTHORITY TO BIND THAT COMPANY.`;

export const CLAUSE_PAYMENT = `PAYMENT. Client agrees to pay the fees and follow the payment schedule set forth in this Agreement. Unless otherwise stated in writing: (a) all amounts are in U.S. dollars; (b) the project date, crew hold, and delivery timeline are not confirmed until any required deposit or full prepayment is received and cleared; (c) deposits are earned upon receipt and applied to the project fee; (d) balances are due on the dates stated in this Agreement or, if none, before release of final deliverables; (e) ${PRODUCER_LEGAL_NAME} may suspend work, withhold deliverables, and reschedule or cancel the shoot if any payment is late; (f) past-due amounts may accrue interest at the lesser of 1.5% per month or the maximum rate permitted by law, plus reasonable collection costs; (g) Client is responsible for bank fees, chargebacks, and failed payment costs caused by Client; and (h) no setoff, deduction, or withholding is permitted unless required by law.`;

export const CLAUSE_DELIVERABLES = `DELIVERABLES AND ACCEPTANCE. ${PRODUCER_LEGAL_NAME} will deliver the items listed in this Agreement in the formats and quantities stated, or as reasonably interpreted from the project scope. Client will review deliverables within the revision window stated in this Agreement. Unless Client provides written, specific rejection notice within that window describing material non-conformance with the agreed scope, deliverables are deemed accepted. Requests after acceptance, or requests that change concept, script, talent, location, music, length, aspect ratio, or deliverable count, constitute additional work billable at ${PRODUCER_LEGAL_NAME}'s then-current rates. ${PRODUCER_LEGAL_NAME} is not responsible for platform-specific technical requirements not disclosed in writing before delivery.`;

export const CLAUSE_USAGE = `USAGE RIGHTS AND LICENSE. Unless this Agreement expressly states that a full buyout or work-for-hire applies, ${PRODUCER_LEGAL_NAME} and its licensors retain ownership of all raw materials, project files, and intellectual property. Upon full payment, ${PRODUCER_LEGAL_NAME} grants Client the usage rights expressly listed in this Agreement—and no others. Any use beyond those rights (including paid media, boosted posts, whitelisting/influencer ads, broadcast, OTT, out-of-home, print beyond stated limits, sublicensing, AI training, or resale) requires separate written approval and may require additional fees. Client may not remove credits, watermarks, or metadata where provided. Territory, term, media, and exclusivity are limited to what is written in this Agreement.`;

export const CLAUSE_INTELLECTUAL_PROPERTY = `INTELLECTUAL PROPERTY. As between the Parties, ${PRODUCER_LEGAL_NAME} owns all copyrights, trademarks, trade secrets, and other intellectual property in materials created before or outside this project, in production methods, templates, LUTs, presets, and in all raw footage, project files, and outtakes not expressly transferred. If this Agreement specifies a "full buyout" or "work made for hire," ownership transfers only to the extent stated and only after full payment. To the extent any material does not qualify as work made for hire, ${PRODUCER_LEGAL_NAME} assigns copyright to Client only after full payment and only for the usage rights purchased. ${PRODUCER_LEGAL_NAME} retains the non-exclusive right to use finished pieces and behind-the-scenes material for portfolio, demo reel, awards, and marketing unless Client obtains a paid confidentiality restriction in writing.`;

export const CLAUSE_RAW_FOOTAGE = `RAW FOOTAGE AND PROJECT FILES. Raw camera files, audio stems, project archives, color timelines, and source assets are not included unless expressly listed in this Agreement. If available for purchase, pricing, format, and delivery method will be quoted separately. ${PRODUCER_LEGAL_NAME} has no obligation to store project files beyond ninety (90) days after final delivery unless a paid storage agreement exists.`;

export const CLAUSE_REVISIONS = `REVISIONS. Only the number of revision rounds and timeframe stated in this Agreement are included. A "revision round" means one consolidated set of written notes from Client on a delivered version. Revisions are limited to reasonable adjustments within the approved creative direction. New concepts, reshoots, additional edits, extra deliverables, music changes, or re-approval cycles are billable change orders. ${PRODUCER_LEGAL_NAME} may decline requests that violate platform policies, third-party rights, or applicable law.`;

export const CLAUSE_CANCELLATION = `CANCELLATION, RESCHEDULING, AND REFUNDS. Deposits and fees for work already performed are non-refundable. If Client cancels or fails to appear, ${PRODUCER_LEGAL_NAME} may retain all amounts paid and invoice for costs committed or incurred (including crew, talent, location, travel, rental, and subcontractor commitments). Rescheduling requires written approval and may incur fees. ${PRODUCER_LEGAL_NAME} may cancel for non-payment, unsafe conditions, breach, or force majeure, without liability beyond refund of unearned prepaid amounts at ${PRODUCER_LEGAL_NAME}'s discretion.`;

export const CLAUSE_CONFIDENTIALITY = `CONFIDENTIALITY. Each Party will use the other Party's non-public business, financial, and project information only to perform under this Agreement and will not disclose it to third parties except to employees, contractors, or advisors who need to know and are bound by similar obligations. This does not restrict information that is public without breach, independently developed, or rightfully received from a third party. ${PRODUCER_LEGAL_NAME} may identify Client by name and logo in client lists unless Client opts out in writing before delivery.`;

export const CLAUSE_PRIVACY = `PRIVACY AND DATA. Each Party will comply with applicable privacy laws in connection with this project. Client is responsible for: (a) providing any required notices and obtaining any required consents from its customers, employees, guests, or subjects appearing in content; (b) ensuring that personal information shared with ${PRODUCER_LEGAL_NAME} is accurate and lawfully collected; and (c) not instructing ${PRODUCER_LEGAL_NAME} to collect or use data in a way that violates law or platform rules. ${PRODUCER_LEGAL_NAME} processes contact and project data to administer this Agreement, deliver services, issue invoices, and maintain records. ${PRODUCER_LEGAL_NAME} does not sell personal information. ${PRODUCER_LEGAL_NAME} may use subprocessors (e.g., cloud storage, email, payment processors) under reasonable safeguards. Sensitive data (health, financial account, government ID, biometrics) will not be collected unless agreed in writing. Upon written request, ${PRODUCER_LEGAL_NAME} will use reasonable efforts to delete or return Client-provided personal data after project completion, subject to legal retention requirements. Security incidents will be notified without unreasonable delay if legally required. This section does not make ${PRODUCER_LEGAL_NAME} Client's "business associate" under HIPAA unless a separate BAA is executed.`;

export const CLAUSE_TALENT_RELEASES = `TALENT, LOCATION, AND THIRD-PARTY RELEASES. Client warrants that it has obtained—or will obtain before distribution—all necessary permissions, location agreements, music licenses, trademark approvals, union agreements, and talent releases for Client-supplied concepts, locations, products, scripts, and brand assets. ${PRODUCER_LEGAL_NAME}'s fee does not include clearance of Client-provided materials. If ${PRODUCER_LEGAL_NAME} arranges talent or locations, Client will sign or fund any additional releases or fees ${PRODUCER_LEGAL_NAME} reasonably requires before public use. Client indemnifies ${PRODUCER_LEGAL_NAME} for claims arising from Client materials or Client-directed content.`;

export const CLAUSE_LIMITATION = `LIMITATION OF LIABILITY. TO THE MAXIMUM EXTENT PERMITTED BY LAW, NEITHER PARTY WILL BE LIABLE FOR ANY INDIRECT, INCIDENTAL, SPECIAL, CONSEQUENTIAL, EXEMPLARY, OR PUNITIVE DAMAGES, OR FOR LOST PROFITS, REVENUE, DATA, OR GOODWILL, EVEN IF ADVISED OF THE POSSIBILITY. ${PRODUCER_LEGAL_NAME.toUpperCase()}'S TOTAL LIABILITY ARISING OUT OF THIS AGREEMENT WILL NOT EXCEED THE AMOUNTS PAID BY CLIENT TO ${PRODUCER_LEGAL_NAME.toUpperCase()} UNDER THIS PROJECT IN THE TWELVE (12) MONTHS BEFORE THE CLAIM. THESE LIMITS DO NOT APPLY TO GROSS NEGLIGENCE, WILLFUL MISCONDUCT, OR LIABILITY THAT CANNOT BE LIMITED BY LAW.`;

export const CLAUSE_INDEMNIFICATION = `INDEMNIFICATION. Client will defend, indemnify, and hold harmless ${PRODUCER_LEGAL_NAME} and its members, managers, employees, and contractors from claims, damages, losses, and expenses (including reasonable attorneys' fees) arising from: (a) Client's use of deliverables beyond granted rights; (b) Client materials or instructions; (c) Client's failure to obtain releases or licenses; (d) Client's violation of law or third-party rights; or (e) Client's breach of this Agreement. ${PRODUCER_LEGAL_NAME} will promptly notify Client of covered claims and cooperate at Client's expense.`;

export const CLAUSE_FORCE_MAJEURE = `FORCE MAJEURE. Neither Party is liable for delay or failure to perform (except payment obligations) due to events beyond reasonable control, including acts of God, illness, labor disputes, government action, utility or internet failures, severe weather, or equipment failure not caused by negligence. The affected Party will notify the other and use reasonable efforts to resume performance. If force majeure continues more than fourteen (14) days, either Party may cancel the affected services with refund or invoice adjustment for unperformed work.`;

export const CLAUSE_GOVERNING_LAW = `GOVERNING LAW; DISPUTES. This Agreement is governed by the laws of the State of North Carolina, without regard to conflict-of-law principles. The Parties will attempt good-faith negotiation before litigation. EXCEPT WHERE PROHIBITED BY LAW, EACH PARTY WAIVES ANY RIGHT TO A JURY TRIAL. Exclusive venue for any dispute shall be in the state or federal courts located in the county of ${PRODUCER_LEGAL_NAME}'s principal place of business in North Carolina, and each Party consents to personal jurisdiction and service of process in such courts. The prevailing Party may recover reasonable attorneys' fees and costs to the extent permitted by North Carolina law.`;

export const CLAUSE_ELECTRONIC_SIGNATURE = `ELECTRONIC SIGNATURES AND RECORDS. The Parties agree to transact electronically. Electronic signatures and records have the same legal effect as handwritten signatures and paper records under the U.S. E-SIGN Act and applicable state law. Each signer represents they are authorized to bind the Party on whose behalf they sign.`;

export const CLAUSE_EQUIPMENT = `EQUIPMENT. If ${PRODUCER_LEGAL_NAME} equipment is used, the using Party is responsible for reasonable care, theft, loss, and damage caused by negligence or misuse while equipment is in that Party's control. Normal wear is excluded. Replacement or repair may be charged at cost or insured value.`;

export const CLAUSE_CLIENT_OWNERSHIP = `CLIENT RELATIONSHIP. The Party identified in this Agreement as originating or owning the client relationship retains that relationship for future work unless all Parties agree otherwise in writing. This Agreement governs only the listed project.`;

export const CLAUSE_NO_OWNERSHIP = `NO PARTNERSHIP OR AGENCY. Nothing in this Agreement creates a partnership, joint venture, employment, or agency relationship between Parties. Each Party is an independent contractor responsible for its own taxes, insurance, and compliance.`;

export const CLAUSE_PORTFOLIO = `PORTFOLIO AND CREDIT. Unless Client provides written opt-out before delivery, ${PRODUCER_LEGAL_NAME} may display finished work and behind-the-scenes stills in portfolio, website, social media, and award submissions, and may credit its role on the project. Client will not remove ${PRODUCER_LEGAL_NAME} credit where embedded in deliverables without written consent.`;

export const CLAUSE_INTERNAL_PAYMENT = `INTERNAL PAYOUTS. Each Party acknowledges the fee split in this Agreement. Each Party is solely responsible for paying its own crew, contractors, and expenses unless expressly assigned. No Party guarantees another Party's profit. Disputes over internal splits do not entitle any Party to withhold payment owed to Client-facing obligations already agreed with Client.`;

export const CLAUSE_INTERNAL_CONFIDENTIALITY = `INTERNAL CONFIDENTIALITY. Parties will not disclose another Party's non-public pricing, client contact information, or deal terms to third parties except as required to perform the project or as required by law.`;

export const AGREEMENT_PREAMBLE_EQUIPMENT_RENTAL = `This Equipment Rental Agreement ("Agreement") is entered into as of the date of the last signature below by and between ${PRODUCER_LEGAL_NAME}, a North Carolina limited liability company ("Owner"), and the renter identified as a party hereto ("Renter"). Owner and Renter may each be referred to as a "Party" and together as the "Parties."

BY SIGNING BELOW, EACH PARTY ACKNOWLEDGES THAT IT HAS READ, UNDERSTANDS, AND AGREES TO BE BOUND BY THIS AGREEMENT, INCLUDING THE ATTACHED EQUIPMENT SCHEDULE AND ALL INCORPORATED TERMS. THE INDIVIDUAL SIGNING FOR A COMPANY REPRESENTS THAT THEY HAVE AUTHORITY TO BIND THAT COMPANY.`;

export const CLAUSE_EQUIPMENT_RENTAL = `EQUIPMENT RENTAL. Owner agrees to rent to Renter the equipment listed in the Equipment Schedule attached to this Agreement ("Equipment") for the rental period, rates, and locations stated herein. Renter accepts Equipment in the condition noted at pickup. Renter will: (a) use Equipment only for lawful purposes and in a professional manner; (b) not sublease, lend, or transfer Equipment without Owner's written consent; (c) keep Equipment secure and protected from theft, damage, and weather; (d) return Equipment on or before the return date at the agreed location, in substantially the same condition except normal wear; and (e) not alter, repair, or service Equipment without Owner's approval. Late returns may incur the daily late fee stated in this Agreement until Equipment is returned. Owner may inspect Equipment upon return and invoice for repair or replacement if damage exceeds normal wear.`;

export const CLAUSE_EQUIPMENT_RENTAL_DEPOSIT = `DEPOSIT AND PAYMENT. Renter agrees to pay the rental fees, deposit, and any applicable taxes set forth in this Agreement. The deposit secures Renter's obligations and may be applied to unpaid fees, damage, loss, or late return charges. Owner may withhold release of Equipment until deposit and any required prepayment are received and cleared. Rental fees are due as stated in the Payment section. Owner may suspend or terminate the rental and reclaim Equipment if Renter fails to pay or breaches this Agreement.`;

export const CLAUSE_EQUIPMENT_RENTAL_INSURANCE = `INSURANCE AND LIABILITY. Renter is responsible for loss, theft, or damage to Equipment while in Renter's possession or control, except for normal wear and Owner's negligence. If insurance is required by this Agreement, Renter will maintain coverage naming Owner as additional insured or loss payee as Owner may reasonably require, and will provide proof before pickup. TO THE MAXIMUM EXTENT PERMITTED BY LAW, OWNER'S TOTAL LIABILITY FOR THIS RENTAL WILL NOT EXCEED THE RENTAL FEES PAID FOR THE AFFECTED EQUIPMENT IN THIS AGREEMENT.`;

export const AGREEMENT_PREAMBLE_TALENT = `This Talent Agreement ("Agreement") is entered into as of the date of the last signature below by and between ${PRODUCER_LEGAL_NAME}, a North Carolina limited liability company ("Producer"), and the talent identified as a party hereto ("Talent"). Producer and Talent may each be referred to as a "Party" and together as the "Parties."

BY SIGNING BELOW, TALENT ACKNOWLEDGES THAT THEY HAVE READ, UNDERSTAND, AND AGREE TO BE BOUND BY THIS AGREEMENT, INCLUDING ALL APPEARANCE, COMPENSATION, USAGE, AND RELEASE TERMS. IF TALENT IS UNDER EIGHTEEN (18) YEARS OF AGE, A PARENT OR LEGAL GUARDIAN MUST ALSO SIGN.`;

export const CLAUSE_TALENT_APPEARANCE = `TALENT SERVICES AND APPEARANCE. Talent agrees to appear and perform the services described in this Agreement for the project, dates, and location stated herein. Talent will arrive on time, follow reasonable direction of Producer, and conduct themselves professionally. Talent represents that they are at least eighteen (18) years of age, or if a minor, that a parent or legal guardian has authorized this Agreement and will be present as required by law.`;

export const CLAUSE_TALENT_COMPENSATION = `COMPENSATION. Producer agrees to pay Talent the fee and on the schedule stated in this Agreement. Talent is responsible for all taxes arising from compensation paid under this Agreement. Producer may issue an IRS Form 1099 or other required tax reporting if applicable. Payment is contingent on Talent's full performance and return of any Producer property.`;

export const CLAUSE_TALENT_RELEASE = `NAME, LIKENESS, AND RELEASE. Talent grants Producer the right to record, photograph, and use Talent's name, voice, likeness, and performance in connection with the project and in the usage scope stated in this Agreement. Talent releases Producer from claims arising from authorized use of such materials, except for Producer's gross negligence or willful misconduct. Talent will not make public statements that disparage Producer or the project without cause.`;

export const CLAUSE_TALENT_INDEPENDENT = `INDEPENDENT CONTRACTOR. Talent is an independent contractor, not an employee, partner, or agent of Producer. Talent is responsible for their own taxes, insurance, and business expenses unless expressly stated otherwise.`;

export const AGREEMENT_PREAMBLE_CONTRACTOR = `This Contractor Agreement ("Agreement") is entered into as of the date of the last signature below by and between ${PRODUCER_LEGAL_NAME}, a North Carolina limited liability company ("Producer"), and the contractor identified as a party hereto ("Contractor"). Producer and Contractor may each be referred to as a "Party" and together as the "Parties."

BY SIGNING BELOW, CONTRACTOR ACKNOWLEDGES THAT THEY HAVE READ, UNDERSTAND, AND AGREE TO BE BOUND BY THIS AGREEMENT, INCLUDING ALL SERVICE, COMPENSATION, AND INDEPENDENT CONTRACTOR TERMS.`;

export const CLAUSE_CONTRACTOR_SERVICES = `SERVICES. Contractor agrees to perform the services described in this Agreement in a professional and workmanlike manner for the dates and project stated herein. Contractor will supply their own tools and expertise unless otherwise agreed in writing.`;

export const CLAUSE_CONTRACTOR_COMPENSATION = `COMPENSATION. Producer agrees to pay Contractor the fee and on the schedule stated in this Agreement. Contractor is responsible for all taxes arising from compensation paid under this Agreement. Producer may issue an IRS Form 1099-NEC or other required tax reporting if applicable.`;

export const CLAUSE_CONTRACTOR_WORK_FOR_HIRE = `WORK PRODUCT AND OWNERSHIP. Unless otherwise stated, all work product, deliverables, and materials created by Contractor in connection with this project shall be owned by Producer as work made for hire to the fullest extent permitted by law. To the extent any work product does not qualify as work made for hire, Contractor assigns all right, title, and interest to Producer.`;

export const CLAUSE_CONTRACTOR_INDEPENDENT = `INDEPENDENT CONTRACTOR. Contractor is an independent contractor, not an employee, partner, or agent of Producer. Contractor is solely responsible for their own taxes, insurance, licenses, and compliance with applicable law. Contractor will provide a completed IRS Form W-9 before payment if requested by Producer.`;

export const AGREEMENT_PREAMBLE_LOCATION = `This Location and Property Use Agreement ("Agreement") is entered into as of the date of the last signature below by and between ${PRODUCER_LEGAL_NAME}, a North Carolina limited liability company ("Producer"), and the property owner identified as a party hereto ("Owner"). Producer and Owner may each be referred to as a "Party" and together as the "Parties."

BY SIGNING BELOW, OWNER GRANTS THE PERMISSIONS AND ACCEPTS THE TERMS IN THIS AGREEMENT FOR THE LOCATION, PROPS, OR BOTH AS DESCRIBED HEREIN.`;

export const CLAUSE_LOCATION_USE = `LOCATION USE AND ACCESS. Owner grants Producer permission to access and use the property described in this Agreement for the dates, times, and production purposes stated herein. Producer will: (a) use the location only for lawful production activities; (b) comply with reasonable rules provided by Owner; (c) limit crew, equipment, and vehicles to agreed areas; (d) not damage property except normal wear; and (e) restore the location to substantially the same condition at the end of use, except for pre-existing conditions documented in writing.`;

export const CLAUSE_LOCATION_PROP_RENTAL = `PROP RENTAL. If props or set pieces are listed in this Agreement, Owner agrees to make them available for the rental period and rates stated. Producer accepts props in the condition noted. Producer is responsible for loss, theft, or damage to rented props while in Producer's possession except for pre-existing damage or Owner's negligence. Props must be returned on or before the agreed date in substantially the same condition except normal wear.`;

export const CLAUSE_LOCATION_COMPENSATION = `COMPENSATION. Producer agrees to pay Owner the location and/or prop fees stated in this Agreement. Owner is responsible for applicable taxes on amounts received. Producer may issue IRS Form 1099 or other required tax reporting if applicable. Payment may be withheld until this Agreement is signed and any required insurance certificates are provided.`;

export const CLAUSE_LOCATION_RELEASE = `RELEASE AND INDEMNITY. Owner represents that Owner has authority to grant the permissions in this Agreement. Owner releases Producer from claims arising from authorized use of the location and props as described, except for Producer's gross negligence or willful misconduct. Owner will indemnify Producer for claims arising from Owner's misrepresentation of authority, undisclosed hazards, or breach of this Agreement.`;

export const CLAUSE_LOCATION_INSURANCE = `INSURANCE. If insurance is required by this Agreement, Producer will maintain production liability coverage and provide certificates naming Owner as additional insured when reasonably required before access. Owner is responsible for maintaining property insurance on the premises. Neither Party's insurance obligations limit other liability provisions in this Agreement.`;
