import { LightFixture } from "./types";

/** Catalog entries users can add from settings — not persisted until saved. */
export const MOCK_FIXTURE_CATALOG: Omit<
  LightFixture,
  "id" | "userId" | "createdAt" | "updatedAt"
>[] = [
  {
    brand: "Amaran",
    model: "100d / 120d (daylight COB)",
    fixtureType: "COB",
    wattage: 100,
    outputNotes: "Daylight-balanced COB; strong output for key through softbox in small/medium rooms.",
    colorType: "daylight_only",
    fixedCct: 5600,
    mountType: "Bowens",
    modifiersOwned: ["softbox", "lantern", "reflector"],
    controlMethod: "sidus_link",
    batteryCapable: false,
    bestUses: ["key", "fill", "background"],
    roomSizeRating: "medium",
    userNotes: "Do not change CCT — balance room with WB, gels, or dim practicals.",
  },
  {
    brand: "Amaran",
    model: "100x / 120x (bi-color COB)",
    fixtureType: "COB",
    wattage: 100,
    outputNotes: "Bi-color COB; warm/cool motivated light for lifestyle and interview.",
    colorType: "bi_color",
    cctMin: 2700,
    cctMax: 6500,
    mountType: "Bowens",
    modifiersOwned: ["softbox", "diffusion"],
    controlMethod: "sidus_link",
    batteryCapable: false,
    bestUses: ["key", "fill"],
    roomSizeRating: "medium",
  },
  {
    brand: "SmallRig",
    model: "RC 30B",
    fixtureType: "COB",
    wattage: 30,
    outputNotes: "Compact bi-color COB with adjustable beam ~15°–60°.",
    colorType: "bi_color",
    cctMin: 2700,
    cctMax: 6500,
    beamAngleMin: 15,
    beamAngleMax: 60,
    mountType: "1/4-20",
    modifiersOwned: ["barn doors", "diffusion"],
    controlMethod: "bluetooth",
    batteryCapable: true,
    bestUses: ["hair", "accent", "background", "eye_light"],
    roomSizeRating: "small",
  },
  {
    brand: "Practical",
    model: "Table / floor lamp",
    fixtureType: "practical",
    outputNotes: "Warm tungsten-style practical for depth and motivation.",
    colorType: "unknown",
    cctMin: 2700,
    cctMax: 3200,
    fixedCct: 3000,
    mountType: "practical lamp",
    modifiersOwned: [],
    controlMethod: "manual",
    bestUses: ["practical", "background"],
    roomSizeRating: "small",
  },
];

export const WINDOW_DAYLIGHT_ID = "window-daylight-virtual";

export const WINDOW_DAYLIGHT_FIXTURE: LightFixture = {
  id: WINDOW_DAYLIGHT_ID,
  userId: "",
  brand: "Natural",
  model: "Window daylight",
  fixtureType: "other",
  colorType: "daylight_only",
  fixedCct: 5600,
  modifiersOwned: ["sheer curtain", "diffusion"],
  bestUses: ["key", "fill"],
  roomSizeRating: "large",
  userNotes: "Motivated soft key when window is visible in frame.",
  createdAt: {} as LightFixture["createdAt"],
  updatedAt: {} as LightFixture["updatedAt"],
};
